// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJUKIlzkfFlaYlUtXHv5d0r3k9hA7GH2c',
    appId: '1:869227041400:web:be4a9d167733ae4f79938d',
    messagingSenderId: '869227041400',
    projectId: 'test-61392',
    authDomain: 'test-61392.firebaseapp.com',
    storageBucket: 'test-61392.firebasestorage.app',
    measurementId: 'G-LVXBPQWEEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfE6aqWcNXS6iMNKtcqYLZFuoOKGdScjQ',
    appId: '1:869227041400:android:afb5fa2f6d167d9f79938d',
    messagingSenderId: '869227041400',
    projectId: 'test-61392',
    storageBucket: 'test-61392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoCq2sUTNYwLlOHO3MAghPdw9bV1ZN5M',
    appId: '1:869227041400:ios:1af80938652ee9d179938d',
    messagingSenderId: '869227041400',
    projectId: 'test-61392',
    storageBucket: 'test-61392.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoCq2sUTNYwLlOHO3MAghPdw9bV1ZN5M',
    appId: '1:869227041400:ios:1af80938652ee9d179938d',
    messagingSenderId: '869227041400',
    projectId: 'test-61392',
    storageBucket: 'test-61392.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJUKIlzkfFlaYlUtXHv5d0r3k9hA7GH2c',
    appId: '1:869227041400:web:e796c9a361ad8bda79938d',
    messagingSenderId: '869227041400',
    projectId: 'test-61392',
    authDomain: 'test-61392.firebaseapp.com',
    storageBucket: 'test-61392.firebasestorage.app',
    measurementId: 'G-5LTXHC6DWP',
  );
}
